import type {
  ImportLog,
  IptvSource,
  LiveChannel,
  MediaItem,
  OwnerSettings,
  Provider,
} from "@/types/studiohub";

const sampleVideo =
  "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4";

export const providers: Provider[] = [
  {
    id: "provider-plex-free",
    name: "Plex Free Movies & TV",
    slug: "plex-free-movies-tv",
    websiteUrl: "https://watch.plex.tv/",
    logoUrl: "",
    providerType: "free_avod",
    defaultPlaybackType: "external_link",
    defaultAccessType: "no_login_required",
    countryAvailability: ["US", "NL", "Global"],
    isEnabled: true,
    notes:
      "Use official Plex watch pages only. Do not extract or proxy Plex streams.",
  },
  {
    id: "provider-pluto-tv",
    name: "Pluto TV",
    slug: "pluto-tv",
    websiteUrl: "https://pluto.tv/",
    logoUrl: "",
    providerType: "free_live_tv",
    defaultPlaybackType: "external_link",
    defaultAccessType: "no_login_required",
    countryAvailability: ["US", "NL", "Global"],
    isEnabled: true,
    notes:
      "Use official Pluto TV links unless Pluto explicitly provides an allowed embed.",
  },
  {
    id: "provider-internet-archive",
    name: "Internet Archive",
    slug: "internet-archive",
    websiteUrl: "https://archive.org/",
    logoUrl: "",
    providerType: "official_provider",
    defaultPlaybackType: "external_link",
    defaultAccessType: "no_login_required",
    countryAvailability: ["US", "NL", "Global"],
    isEnabled: true,
    notes:
      "Public-domain and open-license links still need owner verification before playback.",
  },
  {
    id: "provider-youtube",
    name: "YouTube",
    slug: "youtube",
    websiteUrl: "https://www.youtube.com/",
    logoUrl: "",
    providerType: "youtube",
    defaultPlaybackType: "youtube_embed",
    defaultAccessType: "no_login_required",
    countryAvailability: ["Global"],
    isEnabled: true,
    notes:
      "Only official YouTube embeds are allowed, and only when the video allows embedding.",
  },
  {
    id: "provider-tubi",
    name: "Tubi",
    slug: "tubi",
    websiteUrl: "https://tubitv.com/",
    logoUrl: "",
    providerType: "free_avod",
    defaultPlaybackType: "external_link",
    defaultAccessType: "optional_login",
    countryAvailability: ["US"],
    isEnabled: true,
    notes:
      "Use official Tubi watch pages. StudioHub does not scrape or embed Tubi video.",
  },
  {
    id: "provider-public-broadcaster",
    name: "Public Broadcaster",
    slug: "public-broadcaster",
    websiteUrl: "https://example.com/provider",
    logoUrl: "",
    providerType: "public_broadcaster",
    defaultPlaybackType: "external_link",
    defaultAccessType: "optional_login",
    countryAvailability: ["NL"],
    isEnabled: true,
    notes:
      "Demo broadcaster entry. Use provider-approved links or embeds only.",
  },
  {
    id: "provider-manual-legal-source",
    name: "Manual Legal Source",
    slug: "manual-legal-source",
    websiteUrl: "https://example.com/legal-source",
    logoUrl: "",
    providerType: "official_provider",
    defaultPlaybackType: "external_link",
    defaultAccessType: "unknown",
    countryAvailability: ["Global"],
    isEnabled: true,
    notes:
      "For owner-entered legal sources where the provider is not listed yet.",
  },
  {
    id: "provider-open-m3u",
    name: "Legal M3U Demo",
    slug: "legal-m3u-demo",
    websiteUrl: "https://example.com/legal-m3u",
    logoUrl: "",
    providerType: "free_live_tv",
    defaultPlaybackType: "external_link",
    defaultAccessType: "unknown",
    countryAvailability: ["Global"],
    isEnabled: false,
    notes: "Existing M3U demo source; not part of official provider scraping.",
  },
];

export const mediaItems: MediaItem[] = [
  {
    id: "movie-public-domain-sample",
    mediaType: "movie",
    title: "Public Domain Feature Sample",
    originalTitle: "Public Domain Feature Sample",
    overview:
      "A mock feature entry for owned, open-license, or public-domain playback. The video file is a CC0 browser sample used only to prove the player behavior.",
    posterTone: "from-emerald-500 via-slate-900 to-cyan-500",
    backdropTone: "from-emerald-950 via-slate-950 to-cyan-950",
    releaseDate: "1968-10-01",
    runtime: 96,
    genres: ["Classic", "Public Domain", "Horror"],
    originalLanguage: "English",
    originCountry: ["US"],
    popularity: 74,
    voteAverage: 7.6,
    sourceType: "public_domain",
    importStatus: "approved",
    legalReviewNotes:
      "Demo item: owner must verify public-domain or open-license status before adding real titles.",
    addedAt: "2026-05-12",
    providerLinks: [
      {
        id: "link-public-domain-sample",
        mediaItemId: "movie-public-domain-sample",
        providerId: "provider-internet-archive",
        providerName: "Internet Archive",
        providerSlug: "internet-archive",
        watchUrl: "https://archive.org/",
        playbackType: "public_domain_video",
        accessType: "no_login_required",
        sourceType: "public_domain",
        videoUrl: sampleVideo,
        isFree: true,
        isLegalConfirmed: true,
        availabilityCountry: ["Global"],
        notes:
          "Demo public-domain/open-license player. Replace only with verified legal media.",
        lastCheckedAt: "2026-05-14",
      },
    ],
  },
  {
    id: "movie-big-buck-bunny",
    mediaType: "movie",
    title: "Big Buck Bunny",
    originalTitle: "Big Buck Bunny",
    overview:
      "Open movie metadata demo using an official embeddable YouTube source. Embedding must remain provider-approved in production.",
    posterTone: "from-amber-400 via-zinc-950 to-rose-500",
    backdropTone: "from-amber-950 via-zinc-950 to-rose-950",
    releaseDate: "2008-04-10",
    runtime: 10,
    genres: ["Animation", "Family", "Open Movie"],
    originalLanguage: "English",
    originCountry: ["NL"],
    popularity: 66,
    voteAverage: 7.2,
    sourceType: "youtube",
    importStatus: "approved",
    addedAt: "2026-05-10",
    providerLinks: [
      {
        id: "link-bbb-youtube",
        mediaItemId: "movie-big-buck-bunny",
        providerId: "provider-youtube",
        providerName: "YouTube",
        providerSlug: "youtube",
        watchUrl: "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
        playbackType: "youtube_embed",
        accessType: "no_login_required",
        sourceType: "youtube",
        youtubeVideoId: "aqz-KE-bpKQ",
        isFree: true,
        isLegalConfirmed: true,
        availabilityCountry: ["Global"],
        notes:
          "Official YouTube embed demo. Production items must allow embedding.",
        lastCheckedAt: "2026-05-15",
      },
    ],
  },
  {
    id: "movie-official-provider-link",
    mediaType: "movie",
    title: "Official Provider Link Demo",
    overview:
      "A legal external-link entry. StudioHub does not scrape or play provider content when the provider page is the authorized watch surface.",
    posterTone: "from-sky-500 via-slate-950 to-violet-500",
    backdropTone: "from-sky-950 via-slate-950 to-violet-950",
    releaseDate: "2024-03-19",
    runtime: 84,
    genres: ["Documentary", "Culture"],
    originalLanguage: "English",
    originCountry: ["GB"],
    popularity: 58,
    voteAverage: 6.9,
    sourceType: "official_provider",
    importStatus: "approved",
    addedAt: "2026-05-08",
    providerLinks: [
      {
        id: "link-official-plex",
        mediaItemId: "movie-official-provider-link",
        providerId: "provider-plex-free",
        providerName: "Plex Free Movies & TV",
        providerSlug: "plex-free-movies-tv",
        watchUrl: "https://watch.plex.tv/movie/example-demo",
        playbackType: "external_link",
        accessType: "no_login_required",
        sourceType: "official_provider",
        isFree: true,
        isLegalConfirmed: true,
        availabilityCountry: ["Global"],
        notes:
          "Demo placeholder. Use a real official Plex watch page only after legal review.",
        lastCheckedAt: "2026-05-13",
      },
      {
        id: "link-official-pluto",
        mediaItemId: "movie-official-provider-link",
        providerId: "provider-pluto-tv",
        providerName: "Pluto TV",
        providerSlug: "pluto-tv",
        watchUrl: "https://pluto.tv/on-demand/movies/example-demo",
        playbackType: "external_link",
        accessType: "no_login_required",
        sourceType: "official_provider",
        isFree: true,
        isLegalConfirmed: true,
        availabilityCountry: ["Global"],
        notes:
          "Demo placeholder. StudioHub opens Pluto TV instead of scraping streams.",
        lastCheckedAt: "2026-05-13",
      },
      {
        id: "link-official-tubi",
        mediaItemId: "movie-official-provider-link",
        providerId: "provider-tubi",
        providerName: "Tubi",
        providerSlug: "tubi",
        watchUrl: "https://tubitv.com/movies/example-demo",
        playbackType: "external_link",
        accessType: "optional_login",
        sourceType: "official_provider",
        isFree: true,
        isLegalConfirmed: true,
        availabilityCountry: ["US"],
        notes:
          "Demo placeholder. Use official Tubi pages only; no extraction or embedding.",
        lastCheckedAt: "2026-05-13",
      },
    ],
  },
  {
    id: "movie-manual-review",
    mediaType: "movie",
    title: "Manual Review Placeholder",
    overview:
      "A hidden review example. It stays out of discovery until the owner confirms legal access and approves it.",
    posterTone: "from-stone-500 via-zinc-950 to-red-500",
    backdropTone: "from-stone-950 via-zinc-950 to-red-950",
    releaseDate: "2021-06-22",
    runtime: 72,
    genres: ["Review Queue", "Manual"],
    originalLanguage: "Spanish",
    originCountry: ["ES"],
    popularity: 22,
    voteAverage: 0,
    sourceType: "manual",
    importStatus: "pending_review",
    legalReviewNotes: "Pending legal confirmation.",
    addedAt: "2026-05-15",
    providerLinks: [
      {
        id: "link-manual-review",
        mediaItemId: "movie-manual-review",
        providerId: "provider-manual-legal-source",
        providerName: "Manual Legal Source",
        providerSlug: "manual-legal-source",
        playbackType: "external_link",
        accessType: "unknown",
        sourceType: "manual",
        isFree: false,
        isLegalConfirmed: false,
        availabilityCountry: [],
        notes: "Pending legal confirmation.",
      },
    ],
  },
  {
    id: "tv-public-broadcast-archive",
    mediaType: "tv",
    title: "Public Broadcast Archive",
    overview:
      "A mock TV collection for official public broadcaster links. Episodes open at the provider until an approved embed is available.",
    posterTone: "from-blue-500 via-slate-950 to-teal-500",
    backdropTone: "from-blue-950 via-slate-950 to-teal-950",
    releaseDate: "2022-01-21",
    numberOfSeasons: 3,
    genres: ["Documentary", "Public Broadcaster"],
    originalLanguage: "Dutch",
    originCountry: ["NL"],
    popularity: 69,
    voteAverage: 7.4,
    sourceType: "official_provider",
    importStatus: "approved",
    addedAt: "2026-05-13",
    providerLinks: [
      {
        id: "link-tv-public-broadcast",
        mediaItemId: "tv-public-broadcast-archive",
        providerId: "provider-public-broadcaster",
        providerName: "Public Broadcaster",
        providerSlug: "public-broadcaster",
        watchUrl: "https://example.com/provider/show",
        playbackType: "external_link",
        accessType: "optional_login",
        sourceType: "official_provider",
        isFree: true,
        isLegalConfirmed: true,
        availabilityCountry: ["NL"],
        notes:
          "Demo public broadcaster URL. Replace with an official provider page.",
      },
    ],
  },
  {
    id: "tv-official-embed-sample",
    mediaType: "tv",
    title: "Official Embed Series Sample",
    overview:
      "A series entry showing how approved embeds will look. Real embed URLs must come from the provider's allowed embed tools.",
    posterTone: "from-fuchsia-500 via-slate-950 to-orange-500",
    backdropTone: "from-fuchsia-950 via-slate-950 to-orange-950",
    releaseDate: "2020-09-04",
    numberOfSeasons: 1,
    genres: ["Education", "Open Web"],
    originalLanguage: "English",
    originCountry: ["US"],
    popularity: 47,
    voteAverage: 7.1,
    sourceType: "other_legal",
    importStatus: "approved",
    addedAt: "2026-05-09",
    providerLinks: [
      {
        id: "link-official-embed-sample",
        mediaItemId: "tv-official-embed-sample",
        providerId: "provider-manual-legal-source",
        providerName: "Manual Legal Source",
        providerSlug: "manual-legal-source",
        watchUrl: "https://example.com/embed-approved",
        playbackType: "official_embed",
        accessType: "no_login_required",
        sourceType: "other_legal",
        embedUrl: "https://www.youtube-nocookie.com/embed/aqz-KE-bpKQ",
        isFree: true,
        isLegalConfirmed: true,
        availabilityCountry: ["Global"],
        notes:
          "Demo official embed. Only provider-approved embed URLs should be used.",
      },
    ],
  },
];

export const liveChannels: LiveChannel[] = [
  {
    id: "live-open-culture",
    name: "Open Culture Live",
    description:
      "Demo legal live channel with a placeholder CC0 stream for player layout only.",
    logoTone: "from-teal-400 to-blue-500",
    category: "Documentaries",
    country: "Global",
    language: "English",
    providerName: "Legal M3U Demo",
    playbackType: "m3u_stream",
    accessType: "no_login_required",
    sourceType: "m3u",
    streamUrl: sampleVideo,
    tvgId: "open-culture.demo",
    tvgName: "Open Culture Live",
    groupTitle: "Documentaries",
    isFree: true,
    isLegalConfirmed: true,
    importStatus: "approved",
    lastCheckedAt: "2026-05-15",
  },
  {
    id: "live-public-news",
    name: "Public News Demo",
    description:
      "Official provider link for a public news stream. Playback opens at the provider.",
    logoTone: "from-sky-400 to-cyan-500",
    category: "News",
    country: "NL",
    language: "Dutch",
    providerName: "Public Broadcaster",
    watchUrl: "https://example.com/provider/live-news",
    playbackType: "external_link",
    accessType: "optional_login",
    sourceType: "official_provider",
    isFree: true,
    isLegalConfirmed: true,
    importStatus: "approved",
    lastCheckedAt: "2026-05-13",
  },
  {
    id: "live-kids-learning",
    name: "Kids Learning Demo",
    description:
      "Approved official embed example. Real channels require provider-approved embed terms.",
    logoTone: "from-amber-300 to-pink-500",
    category: "Kids",
    country: "US",
    language: "English",
    providerName: "Manual Legal Source",
    playbackType: "official_embed",
    accessType: "no_login_required",
    sourceType: "other_legal",
    embedUrl: "https://www.youtube-nocookie.com/embed/aqz-KE-bpKQ",
    isFree: true,
    isLegalConfirmed: true,
    importStatus: "approved",
  },
  {
    id: "live-xtream-placeholder",
    name: "Verified Xtream Demo Channel",
    description:
      "Credential-protected source. Credentials stay server-side.",
    logoTone: "from-fuchsia-500 to-violet-500",
    category: "Entertainment",
    country: "Global",
    language: "English",
    providerName: "Verified Xtream Demo",
    playbackType: "xtream_stream",
    accessType: "owner_credentials_required",
    sourceType: "xtream",
    xtreamStreamId: "demo-stream-id",
    xtreamCategoryId: "demo-category-id",
    isFree: false,
    isLegalConfirmed: true,
    importStatus: "approved",
    legalReviewNotes:
      "Mock-only. No raw Xtream URL or credentials are present in frontend data.",
  },
  {
    id: "live-pending-review",
    name: "Pending Review Channel",
    description: "Imported item waiting for owner approval.",
    logoTone: "from-stone-400 to-red-500",
    category: "Movies",
    country: "Unknown",
    language: "Unknown",
    providerName: "Manual M3U Upload",
    playbackType: "m3u_stream",
    accessType: "unknown",
    sourceType: "m3u",
    isFree: false,
    isLegalConfirmed: false,
    importStatus: "pending_review",
    legalReviewNotes: "Hidden until legal status is confirmed.",
  },
];

export const sources: IptvSource[] = [
  {
    id: "source-m3u-demo",
    name: "Legal M3U Demo",
    sourceType: "m3u_url",
    providerName: "Legal M3U Demo",
    sourceUrl: "https://example.com/legal-playlist.m3u",
    epgUrl: "https://example.com/legal-epg.xml",
    isLegalConfirmed: true,
    isEnabled: true,
    notes: "Placeholder for an authorized free live TV playlist.",
    country: "Global",
    providerWebsite: "https://example.com/legal-m3u",
    legalContactInfo: "Provider terms and license notes go here.",
    lastImportedAt: "2026-05-15 09:30",
    lastTestedAt: "2026-05-15 09:28",
    lastStatus: "success",
    importedItems: 12,
  },
  {
    id: "source-xtream-demo",
    name: "Verified Xtream Demo",
    sourceType: "xtream",
    providerName: "Verified Xtream Demo",
    baseUrl: "https://provider.example.com",
    isLegalConfirmed: true,
    isEnabled: false,
    notes:
      "Fake credentials are never stored in this mock frontend. Future credentials remain server-side only.",
    country: "Global",
    providerWebsite: "https://provider.example.com",
    legalContactInfo: "License confirmation and support contact go here.",
    lastImportedAt: "Not imported",
    lastTestedAt: "Not tested",
    lastStatus: "unknown",
    importedItems: 0,
  },
  {
    id: "source-manual-upload",
    name: "Manual M3U Upload",
    sourceType: "m3u_file",
    providerName: "Manual M3U Upload",
    isLegalConfirmed: false,
    isEnabled: false,
    notes: "Example disabled source awaiting legal confirmation.",
    country: "Unknown",
    lastImportedAt: "2026-05-14 18:12",
    lastTestedAt: "2026-05-14 18:10",
    lastStatus: "failed",
    importedItems: 1,
  },
];

export const importLogs: ImportLog[] = [
  {
    id: "log-1",
    iptvSourceId: "source-m3u-demo",
    importType: "m3u",
    status: "success",
    message: "Parsed legal demo playlist. Imported items remain reviewable.",
    itemsFound: 12,
    itemsImported: 2,
    itemsUpdated: 10,
    itemsFailed: 0,
    createdAt: "2026-05-15 09:30",
  },
  {
    id: "log-2",
    iptvSourceId: "source-manual-upload",
    importType: "m3u",
    status: "failed",
    message: "Legal confirmation missing. Source stayed disabled.",
    itemsFound: 1,
    itemsImported: 0,
    itemsUpdated: 0,
    itemsFailed: 1,
    createdAt: "2026-05-14 18:12",
  },
];

export const ownerSettings: OwnerSettings = {
  preferredLanguages: ["English", "Dutch"],
  preferredCountries: ["NL", "US", "Global"],
  preferredSources: [
    "Plex Free Movies & TV",
    "Pluto TV",
    "YouTube",
    "Tubi",
    "Internet Archive",
  ],
  preferredCategories: ["Documentaries", "Movies", "News"],
  defaultPlaybackPreference: "in_app",
  hideUnknownAccess: true,
  hideUnconfirmedSources: true,
  theme: "dark",
};

export const approvedMedia = mediaItems.filter(
  (item) => item.importStatus === "approved",
);

export const approvedLiveChannels = liveChannels.filter(
  (channel) => channel.importStatus === "approved",
);

export const pendingReviewItems = [
  ...mediaItems
    .filter((item) => item.importStatus === "pending_review")
    .map((item) => ({
      id: item.id,
      title: item.title,
      type: item.mediaType === "movie" ? "Movie" : "TV show",
      source: item.providerLinks[0]?.providerName ?? "Unknown",
      accessType: item.providerLinks[0]?.accessType ?? "unknown",
      sourceType: item.sourceType,
      notes: item.legalReviewNotes ?? "Needs owner review.",
    })),
  ...liveChannels
    .filter((channel) => channel.importStatus === "pending_review")
    .map((channel) => ({
      id: channel.id,
      title: channel.name,
      type: "Live channel",
      source: channel.providerName,
      accessType: channel.accessType,
      sourceType: channel.sourceType,
      notes: channel.legalReviewNotes ?? "Needs owner review.",
    })),
];
